default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: spendee_api_development
  username: postgres
  password: spendee_app
  host: localhost

test:
  <<: *development
  database: spendee_api_test

production:
  url: <%= ENV['DATABASE_URL'] %>

#
